defaultPortal: Jose
portals:
  - name: Jose
    portalId: 4640853
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CM3H--7XMBIIAAUAAAAAAAwY1aCbAiDZ5PgWKO7pDDIUiEkTE5VTMHzHudS37W0AgMQ4H_Q6IQAABEEAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAPEIUSSrhwEBdQ_OWgrtvIaibkEpu2l1KA25hMVIAWgA
        expiresAt: '2023-01-04T17:40:37.464Z'
    personalAccessKey: >-
      CiQ5OGE4NTQ1OS0zYjQ0LTRiZTUtODllYi0wZTEwMzBmYTMwMDAQ1aCbAhjZ5PgWKhkABeaRgjvCVALN3c_N_3wq3Nb2hKXSo1D0SgNuYTE
