defaultPortal: Jose
portals:
  - name: Jose
    portalId: 4640853
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIfk3ObZMBIIAAUAAAAAAAwY1aCbAiDZ5PgWKO7pDDIUjfcvIxPSvtyjM4JBKpKw52VcTNE6IQAABEEAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAPEIU_35Sr2ZZtTXQA8rGDXByT6QaixhKA25hMVIAWgA
        expiresAt: '2023-01-10T18:00:26.890Z'
    personalAccessKey: >-
      CiQ5OGE4NTQ1OS0zYjQ0LTRiZTUtODllYi0wZTEwMzBmYTMwMDAQ1aCbAhjZ5PgWKhkABeaRgjvCVALN3c_N_3wq3Nb2hKXSo1D0SgNuYTE
